server:
  listen: 8080
  workers: 4
  upstreams:
    - id: portfolio
      url: https://abhisheklodhaportfolio.netlify.app

    - id: car-store
      url: https://manageyourcars.netlify.app

    - id: buddyformovies
      url: https://buddyformovies.netlify.app

    - id: todos
      url: https://jsonplaceholder.typicode.com

    - id: comments
      url: https://jsonplaceholder.typicode.com

    - id: posts
      url: https://jsonplaceholder.typicode.com
  
  headers:
    - key: x-forward-for
      value: '$ip'

    - key: Authorization
      value: 'Bearer xyz'  

  rules:   
    - path: /todos
      upstreams: 
       - todos

    - path: /comments
      upstreams: 
       - comments

    - path: /posts
      upstreams: 
       - posts
    - path: /portfolio
      upstreams: 
       - portfolio

    - path: /movies
      upstreams: 
       - buddyformovies

    - path: /cars
      upstreams: 
       - car-store